toggle_on_msg: ~6All players have been vanished.
toggle_off_msg: ~6All players have been revealed.
anti_spam_msg: ~4Do not spam the clock.
anti_spam_interval: 5
item_id: 347
item_on_join: false
item_name: ~6Magic Clock
item_lore: ~4Right click to toggle the clock.
reminder_msg: false
reminder_interval: 30
reminder_msg_on: ~6All players are currently vanished.
reminder_msg_off: ~6All players are currently visible.